site_name: VoteKit
repo_url: https://github.com/mggg/VoteKit
repo_name: mggg/VoteKit


theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
  features:
    - navigation.sections
    - navigation.tabs
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

plugins:
- search
- autorefs
- mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: True
            show_root_full_path: false
            show_root_toc_entry: false

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'index.md'
  - 'getting_started.md'
  - User Guide:
    - 'some_plotting_options.md'
    - 'bg_models_1.md'
    - 'bg_models_2.md'
    - 'bg_from_params.md'
    - 'ballot_graph.md'
  - API Reference:
    - 'api.md'
  - Social Choice Reference:
    - 'SCR_general_vocabulary.md'
    - 'SCR_preference_intervals.md'
    - 'SCR_simplex.md'
    - 'SCR_ballot_generators.md'
    - 'SCR_elections.md'
    - 'SCR_distances.md'
